services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo17
      - POSTGRES_PASSWORD=odoo17@123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Riyadh
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo17 -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 6

  web:
    image: odoo:17.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - TZ=Asia/Riyadh
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:

